In [1]:
from deeputil.datasets import CreditCardCustomers

Using TensorFlow backend.

In [2]:
df = CreditCardCustomers.load_data_as_pandas_df()

Downloaded 2.8 MB dataset with 30000 rows and 25 columns..........

In [3]:
df.shape

(30000, 25)

In [4]:
df.describe

<bound method NDFrame.describe of           ID  LIMIT_BAL  SEX  EDUCATION  MARRIAGE  AGE  PAY_0  PAY_2  PAY_3  \
0          1      20000    2          2         1   24      2      2     -1
1          2     120000    2          2         2   26     -1      2      0
2          3      90000    2          2         2   34      0      0      0
3          4      50000    2          2         1   37      0      0      0
4          5      50000    1          2         1   57     -1      0     -1
5          6      50000    1          1         2   37      0      0      0
6          7     500000    1          1         2   29      0      0      0
7          8     100000    2          2         2   23      0     -1     -1
8          9     140000    2          3         1   28      0      0      2
9         10      20000    1          3         2   35     -2     -2     -2
10        11     200000    2          3         2   34      0      0      2
11        12     260000    2          1         2   51     -1     -1     -1
12        13     630000    2          2         2   41     -1      0     -1
13        14      70000    1          2         2   30      1      2      2
14        15     250000    1          1         2   29      0      0      0
15        16      50000    2          3         3   23      1      2      0
16        17      20000    1          1         2   24      0      0      2
17        18     320000    1          1         1   49      0      0      0
18        19     360000    2          1         1   49      1     -2     -2
19        20     180000    2          1         2   29      1     -2     -2
20        21     130000    2          3         2   39      0      0      0
21        22     120000    2          2         1   39     -1     -1     -1
22        23      70000    2          2         2   26      2      0      0
23        24     450000    2          1         1   40     -2     -2     -2
24        25      90000    1          1         2   23      0      0      0
25        26      50000    1          3         2   23      0      0      0
26        27      60000    1          1         2   27      1     -2     -1
27        28      50000    2          3         2   30      0      0      0
28        29      50000    2          3         1   47     -1     -1     -1
29        30      50000    1          1         2   26      0      0      0
...      ...        ...  ...        ...       ...  ...    ...    ...    ...
29970  29971     360000    1          1         1   34     -1     -1     -1
29971  29972      80000    1          3         1   36      0      0      0
29972  29973     190000    1          1         1   37      0      0      0
29973  29974     230000    1          2         1   35      1     -2     -2
29974  29975      50000    1          2         1   37      1      2      2
29975  29976     220000    1          2         1   41      0      0     -1
29976  29977      40000    1          2         2   47      2      2      3
29977  29978     420000    1          1         2   34      0      0      0
29978  29979     310000    1          2         1   39      0      0      0
29979  29980     180000    1          1         1   32     -2     -2     -2
29980  29981      50000    1          3         2   42      0      0      0
29981  29982      50000    1          2         1   44      1      2      2
29982  29983      90000    1          2         1   36      0      0      0
29983  29984      20000    1          2         1   44     -2     -2     -2
29984  29985      30000    1          2         2   38     -1     -1     -2
29985  29986     240000    1          1         2   30     -2     -2     -2
29986  29987     360000    1          1         2   35     -1     -1     -2
29987  29988     130000    1          1         2   34      0      0      0
29988  29989     250000    1          1         1   34      0      0      0
29989  29990     150000    1          1         2   35     -1     -1     -1
29990  29991     140000    1          2         1   41      0      0      0
29991  29992     210000    1          2         1   34      3      2      2
29992  29993      10000    1          3         1   43      0      0      0
29993  29994     100000    1          1         2   38      0     -1     -1
29994  29995      80000    1          2         2   34      2      2      2
29995  29996     220000    1          3         1   39      0      0      0
29996  29997     150000    1          3         2   43     -1     -1     -1
29997  29998      30000    1          2         2   37      4      3      2
29998  29999      80000    1          3         1   41      1     -1      0
29999  30000      50000    1          2         1   46      0      0      0

       PAY_4             ...              BILL_AMT4  BILL_AMT5  BILL_AMT6  \
0         -1             ...                      0          0          0
1          0             ...                   3272       3455       3261
2          0             ...                  14331      14948      15549
3          0             ...                  28314      28959      29547
4          0             ...                  20940      19146      19131
5          0             ...                  19394      19619      20024
6          0             ...                 542653     483003     473944
7          0             ...                    221       -159        567
8          0             ...                  12211      11793       3719
9         -2             ...                      0      13007      13912
10         0             ...                   2513       1828       3731
11        -1             ...                   8517      22287      13668
12        -1             ...                   6500       6500       2870
13         0             ...                  66782      36137      36894
14         0             ...                  59696      56875      55512
15         0             ...                  28771      29531      30211
16         2             ...                  18338      17905      19104
17        -1             ...                  70074       5856     195599
18        -2             ...                      0          0          0
19        -2             ...                      0          0          0
20         0             ...                  20616      11802        930
21        -1             ...                      0        632        316
22         2             ...                  44006      46905      46012
23        -2             ...                    560          0          0
24        -1             ...                   5398       6360       8292
25         0             ...                  28967      29829      30046
26        -1             ...                    -57        127       -189
27         0             ...                  17878      18931      19617
28        -1             ...                   2040      30430        257
29         0             ...                  17907      18375      11400
...      ...             ...                    ...        ...        ...
29970      0             ...                  49005       8676      19487
29971      0             ...                  69674      71070      73612
29972      0             ...                  29223      19616     148482
29973     -2             ...                      0          0          0
29974      2             ...                   2846       1585       1324
29975     -1             ...                   5924       1759       1824
29976      2             ...                  51259      47151      46934
29977      0             ...                 141695     144839     147954
29978      0             ...                 219409     216540     210675
29979     -2             ...                      0          0          0
29980      0             ...                  50360      19971      19694
29981      2             ...                  28192      22676      14647
29982      0             ...                  11328      12036      14329
29983     -2             ...                   2882       9235       1719
29984     -1             ...                   1993       1907       3319
29985     -2             ...                      0          0          0
29986     -2             ...                      0          0          0
29987      0             ...                 108047      93708      97353
29988      0             ...                 245750     175005     179687
29989     -1             ...                    780          0          0
29990      0             ...                 138262      49675      46121
29991      2             ...                   2500       2500       2500
29992     -2             ...                      0          0          0
29993      0             ...                  70626      69473      55004
29994      2             ...                  77519      82607      81158
29995      0             ...                  88004      31237      15980
29996     -1             ...                   8979       5190          0
29997     -1             ...                  20878      20582      19357
29998      0             ...                  52774      11855      48944
29999      0             ...                  36535      32428      15313

       PAY_AMT1  PAY_AMT2  PAY_AMT3  PAY_AMT4  PAY_AMT5  PAY_AMT6  \
0             0       689         0         0         0         0
1             0      1000      1000      1000         0      2000
2          1518      1500      1000      1000      1000      5000
3          2000      2019      1200      1100      1069      1000
4          2000     36681     10000      9000       689       679
5          2500      1815       657      1000      1000       800
6         55000     40000     38000     20239     13750     13770
7           380       601         0       581      1687      1542
8          3329         0       432      1000      1000      1000
9             0         0         0     13007      1122         0
10         2306        12        50       300      3738        66
11        21818      9966      8583     22301         0      3640
12         1000      6500      6500      6500      2870         0
13         3200         0      3000      3000      1500         0
14         3000      3000      3000      3000      3000      3000
15            0      1500      1100      1200      1300      1100
16         3200         0      1500         0      1650         0
17        10358     10000     75940     20000    195599     50000
18            0         0         0         0         0         0
19            0         0         0         0         0         0
20         3000      1537      1000      2000       930     33764
21          316       316         0       632       316         0
22         2007      3582         0      3601         0      1820
23        19428      1473       560         0         0      1128
24         5757         0      5398      1200      2045      2000
25         1973      1426      1001      1432      1062       997
26            0      1000         0       500         0      1000
27         1300      1300      1000      1500      1000      1012
28         3415      3421      2044     30430       257         0
29         1500      1500      1000      1000      1600         0
...         ...       ...       ...       ...       ...       ...
29970     52951     64535      8907        53     19584     16080
29971      2395      2500      2530      2556      3700      3000
29972      2000      3869     25128     10115    148482      4800
29973         0         0         0         0         0         0
29974         0      3000         0         0      1000      1000
29975      8840      6643      5924      1759      1824      7022
29976      4000         0      2000         0      3520         0
29977      7000      7000      5500      5500      5600      5000
29978     10029      9218     10029      8049      8040     10059
29979         0         0         0         0         0         0
29980     10000      4000      5000      3000      4500      2000
29981      2300      1700         0       517       503       585
29982      1500      1500      1500      1200      2500         0
29983      2890      2720      2890      9263      1824      1701
29984       923      2977      1999      3057      3319      1000
29985         0         0         0         0         0         0
29986         0         0         0         0         0         0
29987      3000      2000     93000      4000      5027      4005
29988     65000      8800      9011      6000      7000      6009
29989      9054         0       783         0         0         0
29990      6000      7000      4228      1505      2000      2000
29991         0         0         0         0         0         0
29992      2000         0         0         0         0         0
29993      2000    111784      4000      3000      2000      2000
29994      7000      3500         0      7000         0      4000
29995      8500     20000      5003      3047      5000      1000
29996      1837      3526      8998       129         0         0
29997         0         0     22000      4200      2000      3100
29998     85900      3409      1178      1926     52964      1804
29999      2078      1800      1430      1000      1000      1000

       default payment next month
0                               1
1                               1
2                               0
3                               0
4                               0
5                               0
6                               0
7                               0
8                               0
9                               0
10                              0
11                              0
12                              0
13                              1
14                              0
15                              0
16                              1
17                              0
18                              0
19                              0
20                              0
21                              1
22                              1
23                              1
24                              0
25                              0
26                              1
27                              0
28                              0
29                              0
...                           ...
29970                           0
29971                           0
29972                           0
29973                           1
29974                           1
29975                           0
29976                           1
29977                           0
29978                           0
29979                           0
29980                           0
29981                           0
29982                           1
29983                           0
29984                           0
29985                           0
29986                           0
29987                           0
29988                           0
29989                           0
29990                           0
29991                           1
29992                           0
29993                           0
29994                           1
29995                           0
29996                           0
29997                           1
29998                           1
29999                           1

[30000 rows x 25 columns]>