# keras_vggface Implementation:
https://github.com/rcmalli/keras-vggface

# Oxford VGG_Face:
http://www.robots.ox.ac.uk/~vgg/software/vgg_face/

In [4]:
import numpy as np
from keras.preprocessing import image
from deeputil.modelassist import KerasModelHelper
from deeputil.keras_vggface import vggface

In [2]:
# tensorflow
model = vggface.VGGFace()

Downloading data from https://github.com/rcmalli/keras-vggface/releases/download/v2.0/rcmalli_vggface_tf_v2.h5
579780608/580070376 [============================>.] - ETA: 0s

In [3]:
model

In [5]:
KerasModelHelper.get_model_layers_details_all(model)

Collecting layer count.....
Total 26 layers details are collected.

,Id,LayerName,Type,Filters,InputShape,OutputShape,Activation,ParameterCount
0,0,input_1,InputLayer,0,"(None, 224, 224, 3)","(None, 224, 224, 3)",None,0
1,1,conv1_1,Conv2D,64,"(None, 224, 224, 3)","(None, 224, 224, 64)",relu,1792
2,2,conv1_2,Conv2D,64,"(None, 224, 224, 64)","(None, 224, 224, 64)",relu,36928
3,3,pool1,MaxPooling2D,0,"(None, 224, 224, 64)","(None, 112, 112, 64)",None,0
4,4,conv2_1,Conv2D,128,"(None, 112, 112, 64)","(None, 112, 112, 128)",relu,73856
5,5,conv2_2,Conv2D,128,"(None, 112, 112, 128)","(None, 112, 112, 128)",relu,147584
6,6,pool2,MaxPooling2D,0,"(None, 112, 112, 128)","(None, 56, 56, 128)",None,0
7,7,conv3_1,Conv2D,256,"(None, 56, 56, 128)","(None, 56, 56, 256)",relu,295168
8,8,conv3_2,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
9,9,conv3_3,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
10,10,pool3,MaxPooling2D,0,"(None, 56, 56, 256)","(None, 28, 28, 256)",None,0
11,11,conv4_1,Conv2D,512,"(None, 28, 28, 256)","(None, 28, 28, 512)",relu,1180160
12,12,conv4_2,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
13,13,conv4_3,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
14,14,pool4,MaxPooling2D,0,"(None, 28, 28, 512)","(None, 14, 14, 512)",None,0
15,15,conv5_1,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
16,16,conv5_2,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
17,17,conv5_3,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
18,18,pool5,MaxPooling2D,0,"(None, 14, 14, 512)","(None, 7, 7, 512)",None,0
19,19,flatten,Flatten,0,"(None, 7, 7, 512)","(None, 25088)",None,0
20,20,fc6,Dense,0,"(None, 25088)","(None, 4096)",linear,102764544
21,21,fc6/relu,Activation,0,"(None, 4096)","(None, 4096)",relu,0
22,22,fc7,Dense,0,"(None, 4096)","(None, 4096)",linear,16781312
23,23,fc7/relu,Activation,0,"(None, 4096)","(None, 4096)",relu,0
24,24,fc8,Dense,0,"(None, 4096)","(None, 2622)",linear,10742334
25,25,fc8/softmax,Activation,0,"(None, 2622)","(None, 2622)",relu,0

In [9]:
img_url = "/Users/avkashchauhan/Downloads/Donald-Trump.jpg"
#img_url = "/Users/avkashchauhan/Downloads/Avkash-With-Mug.png"

In [10]:
img = image.load_img(img_url, target_size=(224, 224))

In [11]:
x = image.img_to_array(img)
x = np.expand_dims(x, axis=0)
# TF order aka 'channel-last'
x = x[:, :, :, ::-1]
# TH order aka 'channel-first'
# x = x[:, ::-1, :, :]
# Zero-center by mean pixel
x[:, 0, :, :] -= 93.5940
x[:, 1, :, :] -= 104.7624
x[:, 2, :, :] -= 129.1863

preds = model.predict(x)
print('Predicted:', np.argmax(preds[0]))

Predicted: 176