# API to load VGG16 and VGG19 ImageNet Models

You just need to call the following API:
    
 - ModelsMaster.get_vgg16_model
 - ModelsMaster.get_vgg19_model

In [17]:
import tensorflow
import keras
from deeputil.model import ModelsMaster
from deeputil.modelassist import KerasModelHelper
from deeputil.modelassist import ImportExport

In [2]:
vgg16_model = ModelsMaster.get_vgg16_model()

VGG16 model is ~0.5GB, make sure you have time and space...

In [3]:
KerasModelHelper.get_model_layers_details_all(vgg16_model)

Collecting layer count.....
Total 23 layers details are collected.

,Id,LayerName,Type,Filters,InputShape,OutputShape,Activation,ParameterCount
0,0,input_1,InputLayer,0,"(None, 224, 224, 3)","(None, 224, 224, 3)",None,0
1,1,block1_conv1,Conv2D,64,"(None, 224, 224, 3)","(None, 224, 224, 64)",relu,1792
2,2,block1_conv2,Conv2D,64,"(None, 224, 224, 64)","(None, 224, 224, 64)",relu,36928
3,3,block1_pool,MaxPooling2D,0,"(None, 224, 224, 64)","(None, 112, 112, 64)",None,0
4,4,block2_conv1,Conv2D,128,"(None, 112, 112, 64)","(None, 112, 112, 128)",relu,73856
5,5,block2_conv2,Conv2D,128,"(None, 112, 112, 128)","(None, 112, 112, 128)",relu,147584
6,6,block2_pool,MaxPooling2D,0,"(None, 112, 112, 128)","(None, 56, 56, 128)",None,0
7,7,block3_conv1,Conv2D,256,"(None, 56, 56, 128)","(None, 56, 56, 256)",relu,295168
8,8,block3_conv2,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
9,9,block3_conv3,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
10,10,block3_pool,MaxPooling2D,0,"(None, 56, 56, 256)","(None, 28, 28, 256)",None,0
11,11,block4_conv1,Conv2D,512,"(None, 28, 28, 256)","(None, 28, 28, 512)",relu,1180160
12,12,block4_conv2,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
13,13,block4_conv3,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
14,14,block4_pool,MaxPooling2D,0,"(None, 28, 28, 512)","(None, 14, 14, 512)",None,0
15,15,block5_conv1,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
16,16,block5_conv2,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
17,17,block5_conv3,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
18,18,block5_pool,MaxPooling2D,0,"(None, 14, 14, 512)","(None, 7, 7, 512)",None,0
19,19,flatten,Flatten,0,"(None, 7, 7, 512)","(None, 25088)",None,0
20,20,fc1,Dense,0,"(None, 25088)","(None, 4096)",relu,102764544
21,21,fc2,Dense,0,"(None, 4096)","(None, 4096)",relu,16781312
22,22,predictions,Dense,0,"(None, 4096)","(None, 1000)",softmax,4097000

In [4]:
vgg19_model = ModelsMaster.get_vgg19_model(show_info=False)

In [5]:
KerasModelHelper.get_model_layers_details_all(vgg19_model)

Collecting layer count.....
Total 26 layers details are collected.

,Id,LayerName,Type,Filters,InputShape,OutputShape,Activation,ParameterCount
0,0,input_2,InputLayer,0,"(None, 224, 224, 3)","(None, 224, 224, 3)",None,0
1,1,block1_conv1,Conv2D,64,"(None, 224, 224, 3)","(None, 224, 224, 64)",relu,1792
2,2,block1_conv2,Conv2D,64,"(None, 224, 224, 64)","(None, 224, 224, 64)",relu,36928
3,3,block1_pool,MaxPooling2D,0,"(None, 224, 224, 64)","(None, 112, 112, 64)",None,0
4,4,block2_conv1,Conv2D,128,"(None, 112, 112, 64)","(None, 112, 112, 128)",relu,73856
5,5,block2_conv2,Conv2D,128,"(None, 112, 112, 128)","(None, 112, 112, 128)",relu,147584
6,6,block2_pool,MaxPooling2D,0,"(None, 112, 112, 128)","(None, 56, 56, 128)",None,0
7,7,block3_conv1,Conv2D,256,"(None, 56, 56, 128)","(None, 56, 56, 256)",relu,295168
8,8,block3_conv2,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
9,9,block3_conv3,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
10,10,block3_conv4,Conv2D,256,"(None, 56, 56, 256)","(None, 56, 56, 256)",relu,590080
11,11,block3_pool,MaxPooling2D,0,"(None, 56, 56, 256)","(None, 28, 28, 256)",None,0
12,12,block4_conv1,Conv2D,512,"(None, 28, 28, 256)","(None, 28, 28, 512)",relu,1180160
13,13,block4_conv2,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
14,14,block4_conv3,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
15,15,block4_conv4,Conv2D,512,"(None, 28, 28, 512)","(None, 28, 28, 512)",relu,2359808
16,16,block4_pool,MaxPooling2D,0,"(None, 28, 28, 512)","(None, 14, 14, 512)",None,0
17,17,block5_conv1,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
18,18,block5_conv2,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
19,19,block5_conv3,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
20,20,block5_conv4,Conv2D,512,"(None, 14, 14, 512)","(None, 14, 14, 512)",relu,2359808
21,21,block5_pool,MaxPooling2D,0,"(None, 14, 14, 512)","(None, 7, 7, 512)",None,0
22,22,flatten,Flatten,0,"(None, 7, 7, 512)","(None, 25088)",None,0
23,23,fc1,Dense,0,"(None, 25088)","(None, 4096)",relu,102764544
24,24,fc2,Dense,0,"(None, 4096)","(None, 4096)",relu,16781312
25,25,predictions,Dense,0,"(None, 4096)","(None, 1000)",softmax,4097000

In [12]:
# Now we are loading the VGG19 Model with no Top
vgg19_model_noTop = ModelsMaster.get_vgg19_model(show_info=False, include_top=False)

In [13]:
# As you can see below, the flatten and dense layers are not loaded:
KerasModelHelper.get_model_layers_details_all(vgg19_model_noTop)

Collecting layer count.....
Total 22 layers details are collected.

,Id,LayerName,Type,Filters,InputShape,OutputShape,Activation,ParameterCount
0,0,input_6,InputLayer,0,"(None, None, None, 3)","(None, None, None, 3)",None,0
1,1,block1_conv1,Conv2D,64,"(None, None, None, 3)","(None, None, None, 64)",relu,1792
2,2,block1_conv2,Conv2D,64,"(None, None, None, 64)","(None, None, None, 64)",relu,36928
3,3,block1_pool,MaxPooling2D,0,"(None, None, None, 64)","(None, None, None, 64)",None,0
4,4,block2_conv1,Conv2D,128,"(None, None, None, 64)","(None, None, None, 128)",relu,73856
5,5,block2_conv2,Conv2D,128,"(None, None, None, 128)","(None, None, None, 128)",relu,147584
6,6,block2_pool,MaxPooling2D,0,"(None, None, None, 128)","(None, None, None, 128)",None,0
7,7,block3_conv1,Conv2D,256,"(None, None, None, 128)","(None, None, None, 256)",relu,295168
8,8,block3_conv2,Conv2D,256,"(None, None, None, 256)","(None, None, None, 256)",relu,590080
9,9,block3_conv3,Conv2D,256,"(None, None, None, 256)","(None, None, None, 256)",relu,590080
10,10,block3_conv4,Conv2D,256,"(None, None, None, 256)","(None, None, None, 256)",relu,590080
11,11,block3_pool,MaxPooling2D,0,"(None, None, None, 256)","(None, None, None, 256)",None,0
12,12,block4_conv1,Conv2D,512,"(None, None, None, 256)","(None, None, None, 512)",relu,1180160
13,13,block4_conv2,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
14,14,block4_conv3,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
15,15,block4_conv4,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
16,16,block4_pool,MaxPooling2D,0,"(None, None, None, 512)","(None, None, None, 512)",None,0
17,17,block5_conv1,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
18,18,block5_conv2,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
19,19,block5_conv3,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
20,20,block5_conv4,Conv2D,512,"(None, None, None, 512)","(None, None, None, 512)",relu,2359808
21,21,block5_pool,MaxPooling2D,0,"(None, None, None, 512)","(None, None, None, 512)",None,0

In [20]:
#Now you can use these model as any keras models
assert isinstance(vgg19_model_noTop, keras.engine.training.Model)
assert isinstance(vgg19_model, keras.engine.training.Model)
assert isinstance(vgg16_model, keras.engine.training.Model)